apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnd.fullname" . }}-config
  labels:
  {{- include "lnd.labels" . | nindent 4 }}
data:
  lnd.conf: |-
{{ .Files.Get "config/lnd.conf" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lnd.fullname" . }}-walletpass
  labels:
  {{- include "lnd.labels" . | nindent 4 }}
data:
  .walletpass: |
    {{ .Values.config.walletpass }}
