apiVersion: v1
kind: Service
metadata:
  name: {{include "lnd.fullname"-rpc .}}
  labels: {{- include "lnd.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: rpc
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: rest
  selector: {{- include "lnd.selectorLabels" . | nindent 4}}
