apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "hummingbot.fullname" . }}
  labels:
    {{- include "hummingbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: Parallel
  serviceName: {{ include "hummingbot.fullname" . }}
  # strategy:
  #   type: Recreate
  selector:
    matchLabels:
      {{- include "hummingbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hummingbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hummingbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          stdin: true 
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: hummingbot-conf
            mountPath: {{ .Values.config.conf }}
          - name: hummingbot-logs
            mountPath: {{ .Values.config.logs }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: hummingbot-logs
          emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: hummingbot-conf
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.persistence.storageClassName }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}