apiVersion: v1
kind: Service
metadata:
  name: {{ include "btcpayserver.fullname" . }}-loadbalancer
  labels:
  {{- include "btcpayserver.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "btcpayserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
