apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mev-boost.fullname" . }}
  labels:
    {{- include "mev-boost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "mev-boost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mev-boost.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mev-boost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - "-{{ .Values.boost.chain }}"
            - "-relay-check"
            - "-loglevel=info"
            - "-relays={{ .Values.boost.relay }}"
            - "-addr=0.0.0.0:18550"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector }}
      {{- end }}
