apiVersion: v1
kind: Service
metadata:
  name: {{include "mev-boost.fullname" .}}
  labels: {{- include "mev-boost.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 18550
      targetPort: 18550
      protocol: TCP
      name: mev-boost
  selector: {{- include "mev-boost.selectorLabels" . | nindent 4}}
