apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
    - port: 8551
      targetPort: 8551
      protocol: TCP
      name: engine-rpc
  selector:
    {{- include "besu.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu.fullname" . }}-lb
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
  - name: "rlpx"
    port: 30303
    targetPort: 30303
  selector:
    {{- include "besu.selectorLabels" . | nindent 4 }}
