apiVersion: v1
kind: Service
metadata:
  name: {{ include "besu.fullname" . }}
  labels:
    {{- include "besu.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.validator.ports.monitoring }}
      targetPort: {{ .Values.validator.ports.monitoring }}
      protocol: TCP
      name: monitoring
  selector:
    {{- include "besu.selectorLabels" . | nindent 4 }}
