# Default values for bitcoind.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

debug: false

config:
  printtoconsole: true
  prune: 0
  rpcauth: ""
  whitelist: ""
  p2p:
    enabled: true
    addr: 0.0.0.0
    port: 8333
  rpc:
    enabled: true
    addr: 0.0.0.0
    port: 8332
    allowip: 192.168.0.0/16
  zmqblock:
    enabled: true
    addr: 0.0.0.0
    port: 28332
  zmqtx:
    enabled: true
    addr: 0.0.0.0
    port: 28333
  persistence:
    enabled: true
    ## Set storageClassName if you have no default defined
    #storageClassName: ""
    size: 500Gi

replicaCount: 1

image:
  repository: ruimarinho/bitcoin-core
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 750m
    memory: 1024Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
