nameOverride: ""
fullnameOverride: ""

validator:
  # -- Chain (mainnet | pyrmont)
  chain: "mainnet"
  # -- Terms of use must be set to true. [Terms of service](https://github.com/prysmaticlabs/prysm/blob/master/TERMS_OF_SERVICE.md)
  acceptTermsOfUse: false
  graffiti: ""
  beacon: "prysm-beacon:4000"
  logfile: /data/validator.log
  verbosity: info
  debug:
    # -- Init container (prysm-import) debug
    init: false
    main: false

  image:
    repository: "gcr.io/prysmaticlabs/prysm/validator"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "stable"

  deployment:
    dataDir: "/data"

  persistentVolume:
    storageClassName: ""
    size: 1Gi

  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  ports:
    monitoring: 8081

  nodeSelector: ""

service:
  type: ClusterIP
