apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.http.port }}
      targetPort: {{ .Values.config.http.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.config.ws.port }}
      targetPort: {{ .Values.config.ws.port }}
      protocol: TCP
      name: ws
    - port: {{ .Values.ingress.udp.port }}
      targetPort: {{ .Values.ingress.udp.port }}
      protocol: UDP
      name: p2pudp
    - port: {{ .Values.ingress.tcp.port }}
      targetPort: {{ .Values.ingress.tcp.port }}
      protocol: TCP
      name: p2ptcp
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
