name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
          config: .github/ct.yaml
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          config: .github/ct.yaml
      - name: Run chart-testing (list-changed)
        id: list-changed
        with:
          config: .github/ct.yaml
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        run: ct lint
        with:
          config: .github/ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          config: .github/ct.yaml
      - name: Run chart-testing (install)
        run: ct install
        with:
          config: .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        run: .github/helm-docs.sh

  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.12.10
  #         - v1.13.12
  #         - v1.14.10
  #         - v1.15.11
  #         - v1.16.8
  #         - v1.17.4
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh
