name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch main)
          echo "::set-output name=LIST_CHANGED::$changed"
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        env:
          LIST_CHANGED: ${{ steps.list-changed.outputs.LIST_CHANGED }}
        run: |
          echo "List of changed HELM Charts : $LIST_CHANGED"
          ct lint

  lint-docs:
    runs-on: ubuntu-latest
    needs: lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run helm-docs
        run: .github/helm-docs.sh

  # kubeval-chart:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - lint-chart
  #     - lint-docs
  #   strategy:
  #     matrix:
  #       k8s:
  #         - v1.12.10
  #         - v1.13.12
  #         - v1.14.10
  #         - v1.15.11
  #         - v1.16.8
  #         - v1.17.4
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@master
  #     - name: Run kubeval
  #       env:
  #         KUBERNETES_VERSION: ${{ matrix.k8s }}
  #       run: .github/kubeval.sh
